cliente/src/java/aplicacao/clienteMB.java
package aplicacao;

import java.util.ArrayList;
import java.util.List;
import javax.faces.model.SelectItem;
import javax.inject.Named;
import javax.faces.view.ViewScoped;

/**
 *
 * @author Josias
 */
@Named(value = "clienteMB")
@ViewScoped
public class clienteMB {
    
    private String tipoPessoa = "J";
    private String estado = "SC";
    
    public clienteMB() {
    }

    public String getTipoPessoa() {
        return tipoPessoa;
    }

    public void setTipoPessoa(String tipoPessoa) {
        this.tipoPessoa = tipoPessoa;
    }

    public boolean isPessoaFisica() {
        return "F".equals(tipoPessoa);
    }

    public String getEstado() {
        return estado;
    }

    public void setEstado(String estado) {
        this.estado = estado;
    }

    public List<SelectItem> getCidades() {
        List<SelectItem> cidades = new ArrayList<>();
        if("SC".equals(estado)){
            SelectItem  cidade = new SelectItem("CRI", "Criciúma");
            cidades.add(cidade);
            cidades.add(new SelectItem("ARA", "Araranguá"));
            cidades.add(new SelectItem("URU", "Urussanga"));
        }else if("RS".equals(estado)){
                  SelectItem  cidade = new SelectItem("VIA", "Viamão");
                  cidades.add(cidade);
                  cidades.add(new SelectItem("POA", "Porto Alegre"));
                  cidades.add(new SelectItem("EST", "Esteio"));
        }else if("SP".equals(estado)){
                  SelectItem  cidade = new SelectItem("SAO", "São Paulo");
                  cidades.add(cidade);
                  cidades.add(new SelectItem("GRJ", "Guarujá"));
                  cidades.add(new SelectItem("SAN", "Santos"));
        }
        return cidades;
    }
}

cliente/web/cliente.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:head>
        <!--<script type="text/javascript" src="https://code.jquery.com/jquery.js"></script> -->
        <!--<script type="text/javascript" src="js/bootstrap.min.js"></script> -->

        <title>Cadastro de Cliente</title>

        <!-- Carregando o CSS do Bootstrap -->
        <link href="css/bootstrap.min.css" rel="stylesheet" media="screen" />		
        <!-- jQuery (plugins em JavaScript) -->
        <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
        <!-- componentes JavaScript do bootstrap -->	
        <script type="text/javascript" src="js/bootstrap.min.js"></script>        
    </h:head>
    <h:body>
        <div class="container">
            <div class="page-header">
                <h1>Cadastro de Cliente</h1>
            </div>
            <h:form>
                <div class="row">
                    <div class="col-md-1">
                        <label class="control-label">Código:</label>
                    </div>
                    <div class="col-sm-1">
                        <h:inputText class="form-control"/>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-1">
                        <label class="control-label">Nome:</label>
                    </div>
                    <div class="col-sm-4">
                        <h:inputText class="form-control"/>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-1">
                        <label class="control-label">Telefone:</label> 
                    </div>
                    <div class="col-sm-2">
                        <h:inputText class="form-control"/>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-1">
                        <label class="control-label">Celular:</label> 
                    </div>
                    <div class="col-sm-2">
                        <h:inputText class="form-control"/>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-1">
                        <label class="control-label">E-mail:</label> 
                    </div>
                    <div class="col-sm-4">
                        <h:inputText class="form-control"/>
                    </div>
                </div>
                <hr />
                <div class="row">
                    <div class="col-md-2">
                        <label class="control-label"><h4>Tipo de Pessoa</h4></label>
                    </div>
                    <div class="list-group">
                        <h:selectOneMenu class="list-group-item" onchange="submit()" value="#{clienteMB.tipoPessoa}">
                            <f:selectItem itemLabel="Física" itemValue="F" />
                            <f:selectItem itemLabel="Jurídica" itemValue="J" />
                        </h:selectOneMenu>
                    </div>
                </div>
                <h:panelGroup rendered="#{clienteMB.pessoaFisica}" >
                    <div class="row">
                        <div class="col-md-2">
                            <label class="control-label"><h4>Pessoa Física</h4></label>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-1">
                            <label class="control-label">CPF</label> 
                        </div>
                        <div class="col-sm-2">
                            <h:inputText class="form-control"/> 
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-1">
                            <label class="control-label">RG</label> 
                        </div>
                        <div class="col-sm-2">
                            <h:inputText class="form-control"/> 
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-1">
                            <label class="control-label">Sexo</label>
                        </div>
                        <div>
                            <h:selectOneRadio> 
                                <f:selectItem itemLabel="Feminino" itemValue="F"/>
                                <f:selectItem itemLabel="Masculino" itemValue="M"/>
                            </h:selectOneRadio>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-1">
                            <label>Data de Nascimento:</label>
                        </div>
                        <div class="col-sm-2">
                            <h:inputText class="form-control"/>
                        </div>
                    </div>
                </h:panelGroup>
                <h:panelGroup rendered="#{!clienteMB.pessoaFisica}" >
                    <div class="row">
                        <div class="col-md-2">
                            <label class="control-label"><h4>Pessoa jurídica</h4></label>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-1">
                            <label class="control-label">CNPJ</label> 
                        </div>
                        <div class="col-sm-2">
                            <h:inputText class="form-control"/>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-1">
                            <label class="control-label">Nome Fantasia</label> 
                        </div>
                        <div class="col-sm-4">
                            <h:inputText class="form-control"/>
                        </div>
                    </div>
                </h:panelGroup>
                <hr />
                <div class="row">
                    <div class="col-sm-1">
                        <label class="control-label">Estado</label>
                    </div>
                    <div class="dropdown-menu-right">
                        <h:selectOneMenu class="list-group-item" onchange="submit()" value="#{clienteMB.estado}">
                            <f:selectItem itemLabel="Rio Grande do Sul" itemValue="RS"/>
                            <f:selectItem itemLabel="Santa Catarina" itemValue="SC"/>
                            <f:selectItem itemLabel="São Paulo" itemValue="SP"/>
                        </h:selectOneMenu>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-1">
                        <label class="control-label">Cidade</label>
                    </div>
                    <div class="list-group">
                        <h:selectOneMenu class="list-group-item" onchange="submit()" rendered="#{clienteMB.estado == 'SC'}"  >
                            <f:selectItems value="#{clienteMB.cidades}"/>
                        </h:selectOneMenu>
                        <h:selectOneMenu class="list-group-item" onchange="submit()" rendered="#{clienteMB.estado == 'RS'}"  >
                            <f:selectItems value="#{clienteMB.cidades}"/>
                        </h:selectOneMenu>
                        <h:selectOneMenu class="list-group-item" onchange="submit()" rendered="#{clienteMB.estado == 'SP'}"  >
                            <f:selectItems value="#{clienteMB.cidades}"/>
                        </h:selectOneMenu>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-1">
                        <label class="control-label">Time</label>
                    </div>
                    <div class="dropdown-menu-right">
                        <h:selectOneMenu class="list-group-item">
                            <f:selectItem itemLabel="Avaí" itemValue="avai"/>
                            <f:selectItem itemLabel="Criciúma" itemValue="criciuma"/>
                            <f:selectItem itemLabel="Figueirense" itemValue="figueirense"/>
                        </h:selectOneMenu>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-1">
                        <label class="control-label">Religião</label>
                    </div>
                    <div class="dropdown-menu-right">
                        <h:selectOneMenu class="list-group-item">
                            <f:selectItem itemLabel="Budismo" itemValue="budismo"/>
                            <f:selectItem itemLabel="Cristianismo" itemValue="critianismo"/>
                            <f:selectItem itemLabel="Judaísmo" itemValue="judaismo"/>
                        </h:selectOneMenu>
                    </div>
                </div>
            </h:form>
        </div>
    </h:body>
</html>